meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
    Meal_planCreateView,
    Meal_planDeleteView,
    Meal_planDetailView,
    Meal_planListView,
    Meal_planUpdateView
)


urlpatterns = [
    path("", Meal_planListView.as_view(), name="meal_plans_list"),
    path("<int:pk>/", Meal_planDetailView.as_view(), name="meal_plans_detail"),
    path('<int:pk>/delete/', Meal_planDeleteView.as_view(), name='meal_plans_delete'),
    path("<int:pk>/edit/", Meal_planUpdateView.as_view(), name="meal_plans_edit"),
    path("create/", Meal_planCreateView.as_view(), name="meal_plans_new"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipe_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagDetailView,
    TagListView,
    TagDeleteView,
    TagUpdateView
)


urlpatterns = [
    path("", TagListView.as_view(), name="tag_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path('<int:pk>/delete/', TagDeleteView.as_view(), name='tag_delete'),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Meal_plan(models.Model):
    name = models.CharField(max_length=120)
    owner = models.ForeignKey(
        USER_MODEL, 
        related_name='meal_plan', 
        on_delete=models.CASCADE, 
        null=True
        )
    date = models.DateField(null=True)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def __str__(self):
        return self.name + " by " + str(self.owner)

meal_plans/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from meal_plans.models import Meal_plan

# Create your views here.

class Meal_planListView(ListView):
    paginate_by = 2
    model = Meal_plan
    template_name = "meal_plans/list.html"


class Meal_planDetailView(DetailView):
    model = Meal_plan
    template_name = "meal_plans/detail.html"


class Meal_planCreateView(LoginRequiredMixin, CreateView):
    model = Meal_plan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy('meal_plans_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class Meal_planUpdateView(LoginRequiredMixin, UpdateView):
    model = Meal_plan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy('meal_plans_list')


class Meal_planDeleteView(LoginRequiredMixin, DeleteView):
    model = Meal_plan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy('meal_plans_list')
    

meal_plans/templates/meal_plans/delete.html
{% extends 'meal_base.html' %} {% block content%}

<main>
  <form method="post">
    {% csrf_token %}
    <p>Do you really want to DELETE '{{ meal_plan }}'?</p>
    {{ form.as_p }}
    <button class="button">Delete</button>
  </form>
</main>

{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'meal_base.html' %} {% block content%}
{% load markdownify %}


  <main class="recipe-detail">
    <div>
      <a href='{% url 'meal_plans_edit' meal_plan.id %}'>Edit</a>
      <a href='{% url 'meal_plans_delete' meal_plan.id %}'>Delete</a>
    </div>
    {% if recipe.image %}
      <img src="{{ recipe.image }}" class="pull-right">
    {% endif %}
    <h1>{{ meal_plan.name }}</h1>
    <h2>by {{ meal_plan.owner | default_if_none:'Unknown'}}</h2>
    <h2>Date Served</h2>
    <p>
      Meal will be served on {{ meal_plan.date }} 
    </p>
    <h2>Meals Of The Day</h2>
    <p>The meals will be {{ meal_plan.recipes.all }}</p>
  </main>

{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'meal_base.html' %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'meal_base.html' %} {% block content%}

<main class="recipe-grid">
  {% if user.is_authenticated %} {% for meal_plan in meal_plan_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'meal_plans_detail' meal_plan.id %}"
        >{{ meal_plan.name }}</a
      >
    </h2>
  </div>
  {% endfor %} {% endif %}
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
</main>

{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'meal_base.html' %} {% block content%}

    <main class="recipe-form">
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <div class="control">
          <button class="button">Create</button>
        </div>
      </form>
    </main>
  </body>
</html>

{% endblock content %}